TeacherStudentRegistration-main/routes/web.php
<?php

use App\Http\Controllers\CourseController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SectionController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TeacherController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
});
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
    Route::view('profile', 'users.profile')->name('profile');
    Route::put('profile', [ProfileController::class, 'update'])
        ->name('profile.update');

    Route::resource('teacher', TeacherController::class);
    Route::resource('student', StudentController::class);
    Route::resource('section', SectionController::class);
    Route::resource('subject', SubjectController::class);
    Route::resource('course', CourseController::class);
});


require __DIR__ . '/auth.php';

TeacherStudentRegistration-main/app/Http/Livewire/CourseTable.php
<?php

namespace App\Http\Livewire;


use App\Models\Course;
use Livewire\Component;
use Livewire\WithPagination;

class CourseTable extends Component
{
    use WithPagination;
    public $sortBy = 'id';
    public $perPage = 5;
    public $sortDirection = 'desc';
    public $search = '';

    public function render()
    {
        $courses = Course::search($this->search)
        ->orderBy($this->sortBy, $this->sortDirection)
        ->Paginate($this->perPage);
        return view('livewire.course-table', ['courses' => $courses]) ;
    }

    public function sortBy($field){
        $this->sortDirection == 'desc' ? $this->sortDirection = 'asc' : $this->sortDirection = 'desc';
        return $this->sortBy = $field;
    }
    public function updatingSearch()
    {
        $this->resetPage();
    }
}

TeacherStudentRegistration-main/app/Http/Livewire/SectionTable.php
<?php

namespace App\Http\Livewire;
use App\Models\Section;
use Livewire\Component;
use Livewire\WithPagination;

class SectionTable extends Component
{
    use WithPagination;
    public $sortBy = 'id';
    public $perPage = 5;
    public $sortDirection = 'desc';
    public $search = '';

    public function render()
    {
        $sections = Section::search($this->search)->with('yearLevel', 'course')
        ->orderBy($this->sortBy, $this->sortDirection)
        ->Paginate($this->perPage);
        return view('livewire.section-table', ['sections' => $sections]) ;
    }

    public function sortBy($field){
        $this->sortDirection == 'desc' ? $this->sortDirection = 'asc' : $this->sortDirection = 'desc';
        return $this->sortBy = $field;
    }
    public function updatingSearch()
    {
        $this->resetPage();
    }

}

TeacherStudentRegistration-main/app/Http/Livewire/StudentTable.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class StudentTable extends Component
{
    use WithPagination;
    public $sortBy = 'id';
    public $perPage = 5;
    public $sortDirection = 'desc';
    public $search = '';

    public function render()
    {
        $students = User::search($this->search)
        ->whereRoleIs('student')
        ->orderBy($this->sortBy, $this->sortDirection)
        ->Paginate($this->perPage);
        return view('livewire.student-table', compact('students'));
    }

    public function sortBy($field){
        $this->sortDirection == 'desc' ? $this->sortDirection = 'asc' : $this->sortDirection = 'desc';
        return $this->sortBy = $field;
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

}

TeacherStudentRegistration-main/app/Http/Livewire/TeacherTable.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class TeacherTable extends Component
{

    use WithPagination;
    public $sortBy = 'id';
    public $perPage = 5;
    public $sortDirection = 'desc';
    public $search = '';
    public $UserData = '';

    public function render()
    {
        $teachers = User::search($this->search)
        ->whereRoleIs('teacher')
        ->orderBy($this->sortBy, $this->sortDirection)
        ->Paginate($this->perPage);
        return view('livewire.teacher-table', compact('teachers'));
    }

    public function confirmDelete(User $teacher){
         $this->UserData = $teacher->id;
    }

    public function delete(){

        User::find($this->UserData)->delete();
        session()->flash('message', 'sadfasdfasdfa');
        // return redirect()->to('admin/teacher');
    }

    public function sortBy($field){
        $this->sortDirection == 'desc' ? $this->sortDirection = 'asc' : $this->sortDirection = 'desc';
        return $this->sortBy = $field;
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

}

TeacherStudentRegistration-main/resources/views/livewire/course-table.blade.php
<div>
    <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
        <div class="relative flex space-x-4  my-6 mx-6">
            <a href="{{ route('course.create') }}"
                class="bg-green-500 hover:bg-green-700 text-white py-2 px-4 rounded">Add Course</a>
            <x-input wire:model.debounce.300ms="search" id="search" class="absolute right-0 w-1/3" type="search"
                name="search" placeholder="Search Course" :value="old('search')" />
        </div>

        <div class="w-1/6 mx-6 ">
            <select wire:model="perPage"
                class="block appearance-none w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                id="grid-state">
                <option>2</option>
                <option>5</option>
                <option>10</option>
                <option>15</option>
                <option>25</option>
            </select>
            <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                </svg>
            </div>
        </div>

        <div class="p-6 bg-white border-b border-gray-200">
            <div x-data="{ show: true }" x-show.transition.opacity.out.duration.2000ms="show"
                x-init="setTimeout(() => show = false, 3000)">
                <x-success-message />
            </div>
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200 table-auto">
                                <thead class="bg-gray-100">
                                    <tr>
                                        <th wire:click.prevent="sortBy('course_code')"
                                            class="pl-6 py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider cursor-pointer">
                                            Course Code
                                            @include('partials._sort-icon', ['field'=>'course_code'])
                                        </th>
                                        <th wire:click.prevent="sortBy('course_description')"
                                            class="py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider cursor-pointer">
                                            Course Description
                                            @include('partials._sort-icon', ['field'=>'course_description'])
                                        </th>
                                        <th
                                            class="py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider">
                                            Action
                                        </th>


                                    </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                    @foreach ($courses as $course)
                                    <tr>
                                        <td class="px-6 py-4 whitespace-nowrap text-md text-gray-500">
                                            {{ $course->course_code}}
                                        </td>
                                        <td class="py-4 whitespace-nowrap text-md text-gray-500">
                                            {{ $course->course_description}}
                                        </td>
                                        <td class="whitespace-nowrap text-sm font-medium ">
                                            <a href="{{ route('course.edit', $course) }}"
                                                class="bg-indigo-500 hover:bg-indigo-700 text-white hover:text-white-900 rounded-full  px-3">Edit</a>

                                            <form class="inline-block" action="{{ route('course.destroy', $course) }}"
                                                method="POST" onsubmit="return confirm('Are you sure?');">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <input type="submit"
                                                    class="bg-red-500 hover:bg-red-700 text-white hover:text-white-900 rounded-full px-2"
                                                    value="Delete">
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>

                        </div>
                        <div class="mt-4">
                            {{ $courses->links() }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TeacherStudentRegistration-main/resources/views/livewire/section-table.blade.php
<div>
    <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
        <div class="relative flex space-x-4  my-6 mx-6">
            <a href="{{ route('section.create') }}"
                class="bg-green-500 hover:bg-green-700 text-white py-2 px-4 rounded">Add Course</a>
            <x-input wire:model.debounce.300ms="search" id="search" class="absolute right-0 w-1/3" type="search"
                name="search" placeholder="Search Section" :value="old('search')" />
        </div>

        <div class="w-1/6 mx-6 ">
            <select wire:model="perPage"
                class="block appearance-none w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                id="grid-state">
                <option>2</option>
                <option>5</option>
                <option>10</option>
                <option>15</option>
                <option>25</option>
            </select>
            <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                </svg>
            </div>
        </div>
        <div class="p-6 bg-white border-b border-gray-200">
            <div x-data="{ show: true }" x-show.transition.opacity.out.duration.2000ms="show"
                x-init="setTimeout(() => show = false, 3000)">
                <x-success-message />
            </div>
            <div class="flex flex-col">
                <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class=" align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200 table-auto">
                                <thead class="bg-gray-100">
                                    <tr>
                                        <th wire:click.prevent="sortBy('section_description')"
                                            class="pl-6 py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider cursor-pointer">
                                            Section
                                            @include('partials._sort-icon', ['field'=>'section_description'])
                                        </th>
                                        <th wire:click.prevent="sortBy('year_level_id')"
                                            class="py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider cursor-pointer">
                                            Year Level
                                            @include('partials._sort-icon', ['field'=>'year_level_id'])
                                        </th>
                                        <th wire:click.prevent="sortBy('year_level_id')"
                                            class="py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider cursor-pointer">
                                            Course
                                            @include('partials._sort-icon', ['field'=>'year_level_id'])
                                        </th>
                                        <th
                                            class="text-center text-md font-medium text-gray-500 uppercase tracking-wider">
                                            Action
                                        </th>


                                    </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                    @foreach ($sections as $section)
                                    <tr>
                                        <td class="px-6 py-4 whitespace-nowrap text-md text-gray-500">
                                            {{ $section->section_description }}

                                        </td>
                                        <td class="py-4 whitespace-nowrap text-md text-gray-500">
                                            {{ $section->yearLevel->year_description }}
                                        </td>
                                        <td class="py-4 whitespace-nowrap text-md text-gray-500">
                                            {{ $section->course->course_code }}
                                        </td>
                                        <td class="whitespace-nowrap text-center text-sm font-medium">
                                            <a href="{{ route('section.edit', $section) }}"
                                                class="bg-indigo-500 hover:bg-indigo-700 text-white hover:text-white-900 rounded-full  px-3">Edit</a>

                                            <form class="inline-block" action="{{ route('section.destroy', $section) }}"
                                                method="POST" onsubmit="return confirm('Are you sure?');">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <input type="submit"
                                                    class="bg-red-500 hover:bg-red-700 text-white hover:text-white-900 rounded-full  px-2"
                                                    value="Delete">
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>

                        </div>
                        <div class="mt-4">
                            {{ $sections->links() }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TeacherStudentRegistration-main/resources/views/livewire/student-table.blade.php
<div>
    <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
        <div class="relative block my-6 mx-6">
            <a href="{{ route('student.create') }}"
                class="bg-green-500 hover:bg-green-700 text-white  py-2 px-4 rounded">Add Teacher</a>
            <x-input wire:model.debounce.300ms="search" id="search" class="absolute right-0 w-1/3" type="search"
                name="search" placeholder="Search Student" :value="old('search')" />
        </div>

        <div class="w-1/6 mx-6 ">
            <select wire:model="perPage"
                class="block appearance-none w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                id="grid-state">
                <option>2</option>
                <option>5</option>
                <option>10</option>
                <option>15</option>
                <option>25</option>
            </select>
            <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                </svg>
            </div>
        </div>

        <div class="p-6 bg-white border-b border-gray-200">
            <div x-data="{ show: true }" x-show.transition.opacity.out.duration.2000ms="show"
                x-init="setTimeout(() => show = false, 3000)">
                <x-success-message />
            </div>
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200 table-auto">
                                <thead class="bg-gray-100">
                                    <tr>
                                        <th wire:click.prevent="sortBy('first_name')"
                                            class="pl-6 py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider">
                                            Image
                                        </th>
                                        <th wire:click.prevent="sortBy('first_name')"
                                            class="pl-6 py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider">
                                            Name
                                            @include('partials._sort-icon', ['field'=>'first_name'])
                                        </th>
                                        <th wire:click.prevent="sortBy('email')"
                                            class="py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider">
                                            Email
                                            @include('partials._sort-icon', ['field'=>'email'])
                                        </th>
                                        <th wire:click.prevent="sortBy('birthday')"
                                            class=" py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider">
                                            Birthday
                                            @include('partials._sort-icon', ['field'=>'birthday'])
                                        </th>
                                        <th
                                            class="py-3 text-center text-md font-medium text-gray-500 uppercase tracking-wider">
                                            Action
                                        </th>

                                    </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                    @foreach ($students as $student)
                                    <tr>
                                        <td class="px-6 py-4 whitespace-nowrap text-md text-gray-500">

                                            @if (!$student->avatar)
                                            <img src="{{ Avatar::create($student->first_name . ' ' . $student->last_name)->toBase64() }}"
                                                class="mx-2" />
                                            @else
                                            <img src="{{asset('images/profile/'.$student->avatar)}}" alt="User Picture"
                                                class="w-12 h-12 border rounded-full dark:border-coolGray-700 mx-2">
                                            @endif


                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-md text-gray-500">
                                            {{ $student->first_name . " " . $student->last_name}}
                                        </td>
                                        <td class="py-4 whitespace-nowrap text-md text-gray-500">
                                            {{ $student->email}}
                                        </td>
                                        <td class=" py-4 whitespace-nowrap text-md text-gray-500">
                                            {{ $student->birthday->toFormatedDate()}}
                                        </td>

                                        <td class="whitespace-nowrap text-center text-sm font-medium ">
                                            <a href="{{ route('student.edit', $student) }}"
                                                class="bg-indigo-500 hover:bg-indigo-700 text-white hover:text-white-900 rounded-full  px-3">Edit</a>

                                            <form class="inline-block" action="{{ route('student.destroy', $student) }}"
                                                method="POST" onsubmit="return confirm('Are you sure?');">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <input type="submit"
                                                    class="bg-red-500 hover:bg-red-700 text-white hover:text-white-900 rounded-full  px-2"
                                                    value="Delete">
                                            </form>
                                        </td>


                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>

                        </div>
                        <div class="mt-4">
                            {{ $students->links() }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TeacherStudentRegistration-main/resources/views/livewire/teacher-table.blade.php
<div>
    <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
        <div class="relative block my-6 mx-6">
            <a href="{{ route('teacher.create') }}"
                class="bg-green-500 hover:bg-green-700 text-white  py-2 px-4 rounded">Add Teacher</a>
            <x-input wire:model.debounce.300ms="search" id="search" class="absolute right-0 w-1/3" type="search"
                name="search" placeholder="Search Teacher" :value="old('search')" />
        </div>

        <div class="w-1/5 mx-6 ">
            <select wire:model="perPage"
                class="block appearance-none w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                id="grid-state">
                <option>2</option>
                <option>5</option>
                <option>10</option>
                <option>15</option>
                <option>25</option>
            </select>
            <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                </svg>
            </div>
        </div>

        <div class="p-6 bg-white border-b border-gray-200" x-data="{showDeleteModal:false}"
            x-bind:class="{ 'model-open': showDeleteModal }">
            <div x-data="{ show: true }" x-show.transition.opacity.out.duration.2000ms="show"
                x-init="setTimeout(() => show = false, 3000)">
                <x-success-message />
            </div>
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200 table-auto">
                                <thead class="bg-gray-100">
                                    <tr>
                                        <th wire:click.prevent="sortBy('first_name')"
                                            class="pl-6 py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider">
                                            Image
                                        </th>
                                        <th wire:click.prevent="sortBy('first_name')"
                                            class="pl-6 py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider">
                                            Name
                                            @include('partials._sort-icon', ['field'=>'first_name'])
                                        </th>
                                        <th wire:click.prevent="sortBy('email')"
                                            class="py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider">
                                            Email
                                            @include('partials._sort-icon', ['field'=>'email'])
                                        </th>
                                        <th wire:click.prevent="sortBy('birthday')"
                                            class=" py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider">
                                            Birthday
                                            @include('partials._sort-icon', ['field'=>'birthday'])
                                        </th>
                                        <th
                                            class="py-3 text-center text-md font-medium text-gray-500 uppercase tracking-wider">
                                            Action
                                        </th>

                                    </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                    @foreach ($teachers as $teacher)
                                    <tr>
                                        <td class="px-6 py-4 whitespace-nowrap text-md text-gray-500">
                                            @if (!$teacher->avatar)
                                            <img src="{{ Avatar::create($teacher->first_name . ' ' . $teacher->last_name)->toBase64() }}"
                                                class="mx-2" />
                                            @else
                                            <img src="{{asset('images/profile/'.$teacher->avatar)}}" alt="User Picture"
                                                class="w-12 h-12 border rounded-full dark:border-coolGray-700 mx-2">
                                            @endif
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-md text-gray-500">
                                            {{ $teacher->first_name . " " . $teacher->last_name}}
                                        </td>
                                        <td class="py-4 whitespace-nowrap text-md text-gray-500">
                                            {{ $teacher->email}}
                                        </td>
                                        <td class=" py-4 whitespace-nowrap text-md text-gray-500">
                                            {{ $teacher->birthday->toFormatedDate()}}
                                        </td>

                                        <td class="whitespace-nowrap text-center text-sm font-medium ">
                                            <a href="{{ route('teacher.edit', $teacher) }}"
                                                class="bg-indigo-500 hover:bg-indigo-700 text-white hover:text-white-900 rounded-full  px-3">Edit</a>
                                            <button x-on:click="$wire.confirmDelete({{ $teacher }})"
                                                @click={showDeleteModal=true} type="button"
                                                class="bg-red-500 hover:bg-red-700 text-white hover:text-white-900 rounded-full  px-3">Delete</button>

                                        </td>


                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>

                        </div>
                        <div class="mt-4">
                            {{ $teachers->links() }}
                        </div>
                        <x-delete-modal-confirmation />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>