TeacherStudentRegistration-main/routes/web.php
<?php

use App\Http\Controllers\CourseController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SectionController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TeacherController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
});
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
    Route::view('profile', 'users.profile')->name('profile');
    Route::put('profile', [ProfileController::class, 'update'])
        ->name('profile.update');

    Route::resource('teacher', TeacherController::class);
    Route::resource('student', StudentController::class);
    Route::resource('section', SectionController::class);
    Route::resource('subject', SubjectController::class);
    Route::resource('course', CourseController::class);
});


require __DIR__ . '/auth.php';

TeacherStudentRegistration-main/app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Models\User;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
        return view('users.admin.student.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.admin.student.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $student = User::create($request->validated());
        $student->attachRole('student');

        if($request->hasFile('avatar')){
            $avatar =  $student->id . '-'. $request->first_name . '-' . $request->last_name .'.' . $request->avatar->getClientOriginalExtension(); 
            $request->avatar->move(public_path('images/profile'), $avatar);
            $student->update(['avatar'=> $avatar]);
        }
        return redirect()->route('student.index')->with('message', 'Student Add successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $student)
    {
        return view('users.admin.student.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $student)
    {
        $student->update($request->validated());
        return redirect()->route('student.index')->with('message', 'Student Profile Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $student)
    {
        $student->delete();
        return redirect()->route('student.index')->with('message', 'Student Profile Deleted successfully');
    }
}

TeacherStudentRegistration-main/app/Http/Livewire/StudentTable.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class StudentTable extends Component
{
    use WithPagination;
    public $sortBy = 'id';
    public $perPage = 5;
    public $sortDirection = 'desc';
    public $search = '';

    public function render()
    {
        $students = User::search($this->search)
        ->whereRoleIs('student')
        ->orderBy($this->sortBy, $this->sortDirection)
        ->Paginate($this->perPage);
        return view('livewire.student-table', compact('students'));
    }

    public function sortBy($field){
        $this->sortDirection == 'desc' ? $this->sortDirection = 'asc' : $this->sortDirection = 'desc';
        return $this->sortBy = $field;
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

}

TeacherStudentRegistration-main/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

TeacherStudentRegistration-main/resources/views/users/admin/student/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Teacher') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">


                    <x-auth-validation-errors />
                    <form method="POST" action="{{ route('student.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="grid grid-cols-3 gap-6">

                            <div>
                                <x-label for="name" :value="__('First Name')" />
                                <x-input id="first_name" class="block mt-1 w-full" type="text" name="first_name"
                                    autofocus />
                            </div>
                            <div>
                                <x-label for="middle_name" :value="__('Middle Name')" />
                                <x-input id="middle_name" class="block mt-1 w-full" type="text" name="middle_name"
                                    autofocus />
                            </div>
                            <div>
                                <x-label for="last_name" :value="__('Last Name')" />
                                <x-input id="last_name" class="block mt-1 w-full" type="text" name="last_name"
                                    autofocus />
                            </div>

                            <div>
                                <x-label for="email" :value="__('Email')" />
                                <x-input id="email" class="block mt-1 w-full" type="email" name="email" autofocus />
                            </div>
                            <div>
                                <x-label for="birthday" :value="__('Birthday')" />
                                <x-input id="birthday" class="block mt-1 w-full" type="date" name="birthday"
                                    autofocus />
                            </div>
                            <div>
                                <x-label for="avatar" :value="__('Image')" />
                                <x-input id="avatar" class="block mt-1 w-full" type="file" name="avatar"
                                    :value="old('avatar')" />
                            </div>
                        </div>
                        <div class="flex items-center justify-end mt-4">
                            <x-button class="ml-3">
                                {{ __('Create') }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

TeacherStudentRegistration-main/resources/views/users/admin/student/edit.blade.php
<x-app-layout>
  <x-slot name="header">
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
          {{ __('Teacher') }}
      </h2>
  </x-slot>

  <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
          <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
              <div class="p-6 bg-white border-b border-gray-200">

                <x-auth-validation-errors />

                  <form method="POST" action="{{ route('student.update', $student) }}" >
                      @method('PUT')
                      @csrf
                      <div class="grid grid-cols-3 gap-6">

                              <div>
                                  <x-label for="name" :value="__('First Name')" />
                                  <x-input id="first_name" class="block mt-1 w-full" type="text" name="first_name" value="{{ $student->first_name }}" autofocus />
                              </div>
                              <div>
                                  <x-label for="middle_name" :value="__('Middle Name')" />
                                  <x-input id="middle_name" class="block mt-1 w-full" type="text" name="middle_name" value="{{ $student->middle_name }}" autofocus />
                              </div>
                              <div>
                                  <x-label for="last_name" :value="__('Last Name')" />
                                  <x-input id="last_name" class="block mt-1 w-full" type="text" name="last_name" value="{{ $student->last_name }}" autofocus />
                              </div>

                              <div>
                                  <x-label for="email" :value="__('Email')" />
                                  <x-input id="email" class="block mt-1 w-full" type="email" name="email" value="{{ $student->email }}" autofocus />
                              </div>
                              <div>
                                  <x-label for="birthday" :value="__('Birthday')" />
                                  <x-input id="birthday" class="block mt-1 w-full" type="date" name="birthday"  value="{{$student->birthday->format('Y-m-d')}}" autofocus />
                                </div>

                      </div>
                      <div class="flex items-center justify-end mt-4">
                          <x-button class="ml-3">
                              {{ __('Update') }}
                          </x-button>
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
</x-app-layout>

TeacherStudentRegistration-main/resources/views/users/admin/student/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Student') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">


            @livewire('student-table')
        </div>
    </div>

</x-app-layout>